version: "3"
services:
  eureka-serviceregistry:
    build: ./Eureka
    ports:
      - "8761:8761"
    tty: true

  axon-server:
    image: axoniq/axonserver:4.3.2
    ports:
      - 8024:8024
      - 8124:8124

  request:
    build: ./RequestService
    ports:
      - "8086:8086"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  auth:
    build: ./AuthService
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  car-info:
    build: ./CarInfoService
    ports:
      - "8087:8087"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  pki-service:
    build: ./pki
    ports:
      - "8082:8082"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry

  zuul:
    build: ./Zuul
    ports:
      - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - auth

  car-service:
    build: ./AxonSaga/CarService
    ports:
      - "8090:8090"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - AXON_HOST=axon-server
    tty: true
    depends_on:
      - eureka-serviceregistry
      - axon-server

  search-service:
    build: ./AxonSaga/SearchService
    ports:
      - "8084:8084"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      - AXON_HOST=axon-server
    tty: true
    depends_on:
      - eureka-serviceregistry
      - axon-server
