export const SET_KEYUSAGES = "SET_KEYUSAGES";

export const SET_ALL_CERTIFICATES = "SET_ALL_CERTIFICATES";
export const SET_ALL_REVOCATED_CERTS = "SET_ALL_REVOCATED_CERTS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";

export const SET_PROFILE = "SET_PROFILE";

export const SET_CARS = "SET_CARS";

export const SET_RESERVATION_PERIODS = "SET_RESERVATION PERIODS";

export const SET_ADVERTISEMENTS = "SET_ADVERTISEMENTS";
export const SET_ADVERTISEMENTS_CART = "SET_ADVERTISEMENTS_CART";

export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_USER_BLOCKED = "SET_USER_BLOCKED";

export const SET_ALLUSER_DELETE = "SET_ALLUSER_DELETE";

export const SET_ALL_BRANDS = "SET_ALL_BRANDS";
export const SET_ALL_MODELS = "SET_ALL_MODELS";

export const SET_TOKEN_GENERATED = "SET_TOKEN_GENERATED";
export const SET_CART_ITEMS_NUM = "SET_CART_ITEMS_NUM";

export const SET_ADDED_CARS = "SET_ADDED_CARS";

export const SET_PASSED_REQUESTS = "SET_PASSED_REQUESTS";

export const SET_REPORT = "SET_REPORT";

export const SET_ADVERTISEMENT_COMMENTS = "SET_ADVERTISEMENT_COMMENTS";

export const SET_STATISTIC = "SET_STATISTIC";

export const SET_RESERVED_REQUESTS = "SET_RESERVED_REQUESTS";
